=== saadehm80/XML-bourse/bourse.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" >
    <xsd:element name="bourse">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="societe" maxOccurs="unbounded" type="T_SOCIETE">
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:complexType name="T_SOCIETE"> 
        <xsd:sequence>
            <xsd:element name="codeSociete" type="xsd:string"></xsd:element>
            <xsd:element name="nomSociete" type="xsd:string"></xsd:element>
            <xsd:element name="dateIntroduction" type="xsd:date"></xsd:element>            
            <xsd:element name="cotations" type="T_COTATIONS"></xsd:element>
        </xsd:sequence>
        <xsd:attribute name="type" default="Banque">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="Banque"></xsd:enumeration>                    
                    <xsd:enumeration value="Assurance"></xsd:enumeration>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
    </xsd:complexType>
    
    <xsd:complexType name="T_COTATIONS">
        <xsd:sequence>
            <xsd:element name="cotation" type="T_COTATION" maxOccurs="unbounded">
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="T_COTATION">
        <xsd:attribute name="num" type="xsd:int" use="required"> </xsd:attribute>
        <xsd:attribute name="dateCotation" type="xsd:date" use="required"> </xsd:attribute>
        <xsd:attribute name="valeurAction" type="xsd:double" use="required"> </xsd:attribute>
        <!--<xsd:attribute name="valeurAction1" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:double">
                    <xsd:minExclusive value="0"></xsd:minExclusive>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        -->
    </xsd:complexType> 
    
</xsd:schema>

=== saadehm80/XML-bourse/bourse2.xml
<?xml version="1.0" encoding="UTF-8"?>
<bourse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./bourse.xsd">
    <societe type="Banque"> 
        <codeSociete>SGBM</codeSociete>
        <nomSociete>Societe Generale</nomSociete>
        <dateIntroduction>2000-11-01</dateIntroduction>
        <cotations>
            <cotation num="23" dateCotation="2010-01-01" valeurAction="650"></cotation>
            <cotation num="24" dateCotation="2010-01-02" valeurAction="680"></cotation>
        </cotations>
    </societe>
    <societe type="Banque">
        <codeSociete>ASSMAAF</codeSociete>
        <nomSociete>MAIF Assurance</nomSociete>
        <dateIntroduction>2010-11-01</dateIntroduction>
        <cotations>
            <cotation num="43" dateCotation="2020-01-01" valeurAction="550"></cotation>
            <cotation num="44" dateCotation="2021-01-02" valeurAction="380"></cotation>
        </cotations>
    </societe>
</bourse>
